spring:
  profiles:
    include:
    - spring-boot
    - server
    - mvc
    - h2
---
spring:
  profiles:
    active: server
server:
  port: 8001
---
spring:
  profiles:
    active: mvc
  thymeleaf:
    prefix: classpath:/public/
---
spring:
  profiles:
    active: spring-boot
  output:
    ansi:
      enabled: always
---
spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:file:./spring-cloud-gateway-monolith;AUTO_SERVER=TRUE;MULTI_THREADED=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: spring-cloud-gateway-monolith
    password: spring-cloud-gateway-monolith
    #driver-class-name: org.h2.Driver
    hikari.connection-test-query: 'SELECT 1'
logging.level.org.springframework.jdbc: 'DEBUG'
