service:
- docker
env:
  global:
  - TERM=dumb
  - secure: fbt09y7oW/qr2gt7rRx5mYp7N0guNlq4H0hv/i+vegXaBuAKlMkEGPEzmpjW8tgCRQJi/CXpAOuRcWE+JMWXQ0boMdk3fQNQ884QBXj9WVGpZjDBiLXeFD6yztaU57XPwDqXvSHZpVElu00DWpsgk5vuSrK2l/0OohHtQ32q+nXZSZzBlWbxFaMdep4v4LRH9kRD2D84Mub+fkrKSjuA+qlktp5wk+Lv77qB3I6h3OB4XmyA+O6kXJrYszii78x6Yf5RpcZLbUFbshJPOdj0GTpERW1tXMPVkIgYedUZ+jhGwcCHnk0N6L3kUYcSK+ZA/IgFKyC0ea2i5azODgheGIe0lMOrai5ndlgSTvyNj8GVbzTUeY2rOwZ6H52obpvVpDR64DtJPx8h6oj945OED0Aw1dzm6l1PAGvBePIuc3wa99UHkQPOSqab626Y0NRfrY7IDg4nFBLLhNvLbrCmU28pQLKracgl7m6/E8oB/IzdTTcKb1DQFldqPTHPafrWZyDxD0Sv14OcHM8A83C7LEvhPc3R8J459vExoGKZN6f45/JjBN+NlQP8bZ629oY9ZkbWLM1t5UqQ96trSXX2qpJRa75kF2lmsy7k+fvfnnZK38O34eE1sZhF32OQZGKudlwW4xrJdwpA1nbu8RrnTLZfGgyAERR8OMvmpffriww=
language: java
jdk: oraclejdk8
apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip
install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8001 80 8001 80
script:
- bash gradlew >/dev/null
- java -jar ./build/libs/*.jar &
- wait_for 8001
- http :8001
- http :8001/api/
- http :8001/api/contents
- stop_any 8001 80 8001 80
- bash ./build/libs/*.jar &
- wait_for 8001
- http :8001
- http :8001/api/
- http :8001/api/contents
- stop_any 8001 80 8001 80
- bash gradlew composeUp
- http :8001
- http :8001/api/
- http :8001/api/contents
- bash gradlew composeDown
before_deploy: "./gradlew documentation"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages
before_cache:
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
