version: '2.1'

services:

  monolith:
    restart: unless-stopped
    build:
      context: ./ms-0-monolith
      dockerfile: ./Dockerfile
    volumes: ['monolith-data:/home/appuser']
    ports: ['8001:8001']
    networks:
      public-net:
        aliases:
          - m
          - monolith

  gateway:
    restart: unless-stopped
    build:
      context: ./ms-1-gateway
      dockerfile: ./Dockerfile
    volumes: ['gateway-data:/home/appuser']
    ports: ['8002:8002']
    depends_on:
      monolith:
        condition: service_healthy
    links:
      - 'monolith:monolith'
    environment:
      PROPS_MONOLITH_HOST: 'monolith'
    networks:
      public-net:
        aliases:
          - g
          - gateway

  ui:
    restart: unless-stopped
    build:
      context: ./ms-2-ui
      dockerfile: ./Dockerfile
    volumes: ['ui-data:/home/appuser']
    ports: ['8003:8003']
    depends_on:
      gateway:
        condition: service_healthy
    links: ['gateway:gateway']
    environment:
      PROPS_GATEWAY_HOST: 'gateway'
    networks:
      public-net:
        aliases:
          - u
          - ui

  rest:
    restart: unless-stopped
    build:
      context: ./ms-3-rest
      dockerfile: ./Dockerfile
    volumes: ['rest-data:/home/appuser']
    ports: ['8004:8004']
    depends_on:
      gateway:
        condition: service_healthy
    links: ['gateway:gateway']
    environment:
      PROPS_GATEWAY_HOST: 'gateway'
    networks:
      public-net:
        aliases:
          - r
          - rest

volumes:
  monolith-data: {}
  gateway-data: {}
  ui-data: {}
  rest-data: {}

networks:
  public-net:
