spring:
  profiles:
    include:
    - props
    - server
    - spring-boot
    - actuator
    - h2
    - logging
---
spring:
  profiles:
    active: server
server:
  port: ${props.monolith.port}
---
spring:
  profiles:
    active: spring-boot
  application:
    name: monolith
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/public/
---
spring:
  profiles:
    active: actuator
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
    shutdown:
      enabled: false
---
spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:file:./spring-cloud-gateway-monolith;AUTO_SERVER=TRUE;MULTI_THREADED=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: spring-cloud-gateway-monolith
    password: spring-cloud-gateway-monolith
    #driver-class-name: org.h2.Driver
    hikari.connection-test-query: 'SELECT 1'
---
spring:
  profiles:
    active: logging
logging.level.org.springframework.jdbc: 'DEBUG'
