spring:
  profiles:
    include:
    - props
    - server
    - spring-boot
    - spring-cloud
    - actuator
    - logging
---
spring:
  profiles:
    active: server
server:
  port: ${props.ui.port}
---
spring:
  profiles:
    active: spring-boot
  application:
    name: ui
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/public/
---
spring:
  profiles:
    active: spring-cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
    service-registry:
      auto-registration:
        enabled: false
---
spring:
  profiles:
    active: actuator
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
    shutdown:
      enabled: false
---
spring:
  profiles:
    active: logging
logging.level.org.springframework.web: 'DEBUG'
